version: '3.8'
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name:
      gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
#      - "TZ=Europe/Moscow"
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name:
      server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
#      - "TZ=Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres

  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "6541:5432"
    environment:
#      - "TZ=Europe/Moscow"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shareit